project:
  type: website

website:
  title: "我的科研博客"
  navbar:
    left:
      - href: index.qmd
        text: 首页
      - href: posts/welcome.qmd
        text: 文章

format:
  html:
    theme: cosmo
    toc: true
