project:
  type: website

website:
  title: "Dors-Liu Quan的笔记"
  site-url: "https://yourname.github.io"  # 把 yourname 替换成你的 GitHub 用户名
  navbar:
    left:
      - href: posts.qmd
        text: 文章 & 博客
      # - href: index.qmd
      #   text: 首页TODO
    right:
      - href: about.qmd
        text: 关于我
      - icon: rss
        href: index.xml

format:
  html:
    # 支持浅色和深色主题切换
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    highlight-style: espresso
    fig-align: center

comments:
  giscus:
    repo: yourname/yourname.github.io
    repo-id: "R_kgDOPlIFIA"
    category: "Comments"
    category-id: "DIC_kwDOPlIFIM4CusaC"

# 可选：添加全局脚注、执行设置等
